run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: books-api
